[package]
name = "function_string_builder"
version = "1.0.3"
edition = "2021"
description = "A string builder that takes a user-provided function"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
